services:
  neo4j:
    image: neo4j:5.23
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_db_temporal_timezone=UTC
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_PLUGINS=[]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1;"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 6s

  api:
    build: .
    image: neo4j-threat-intel-api:latest
    container_name: threat-intel-api
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - EMBED_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - MULTILINGUAL_EMBED_MODEL=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - CHUNK_SIZE=500
      - CHUNK_OVERLAP=50
    depends_on:
      neo4j:
        condition: service_healthy
    command: >
      uvicorn src.api.api:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

volumes:
  neo4j_data:
  neo4j_logs:
